---

- name: Create Gitlab configuration directory
  file:
    path: "{{ gitlab_config_dir }}"
    state: directory
    mode: 0744
    owner: root
    group: root

- name: Create Gitlab data directory
  file:
    path: "{{ gitlab_data_dir }}"
    state: directory
    mode: 0744
    owner: root
    group: root

- name: Create Gitlab logs directory
  file:
    path: "{{ gitlab_log_dir }}"
    state: directory
    mode: 0744
    owner: root
    group: root

- name: Create Gitlab lfs directory
  file:
    path: "{{ gitlab_lfs_dir }}"
    state: directory

- name: Create Gitlab backups directory
  file:
    path: "{{ gitlab_backups_dir }}"
    state: directory

- name: Create configuration file for Gitlab
  template: src=gitlab.rb.j2 dest={{ gitlab_config_dir }}/gitlab.rb
    owner="root" group="root" mode=0664

- include: docker-compose.yml
  when: gitlab_startup == 'docker-compose'

- include: marathon.yml
  when: gitlab_startup == 'marathon'
