---
#
# Master Install
#
# Installs _the_ world
#

- include: ../../common/playbooks/infrastructure/base-system.yml

- include: ../../common/playbooks/infrastructure/zookeeper.yml

- include: ../../common/playbooks/infrastructure/mesos-leader.yml

- include: ../../common/playbooks/infrastructure/mesos-mixed.yml

- include: ../../common/playbooks/infrastructure/mesos-follower.yml

- include: ../../common/playbooks/mip-services.yml

- include: ../../common/playbooks/algorithm-factory/woken-database.yml

- hosts: demo-db
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: ldsm-database
      tags: ['demo-database', 'database', 'analytics', 'algorithm-factory', 'af', 'marathon-app']

- include: ../../common/playbooks/algorithm-factory/woken.yml

- include: ../../common/playbooks/algorithm-factory/woken-validation.yml
