---

- hosts: database
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/roles/versions.yml"

  roles:

    - role: postgres
      tags: ['database', 'analytics']

    - role: audit-deployment
      installed_component: analytics-database-server
      tags: ['database', 'analytics']
