---

- hosts: managed
  become: yes

  tasks:

    - name: Gather information from target server
      setup:

    - name: Suggested target server hostname
      debug: var=ansible_hostname

    - name: Suggested target server DNS
      debug: var=ansible_fqdn

    - name: Suggested target server IP address
      debug:
        msg: "{{ ansible_default_ipv4.address }}"

- hosts: localhost
  become: no
  vars_prompt:
    - name: "server_hostname"
      prompt: "Target server hostname"
      private: no
    - name: "server_dns"
      prompt: "Target server DNS. You can use the IP address if DNS is not setup for this server"
      private: no
    - name: "server_ip_address"
      prompt: "Target server IP address"
      private: no
    - name: "gitlab_com_login"
      prompt: "Username on Gitlab to download private Docker images. Leave blank if you do not have access to this information"
      private: no
    - name: "gitlab_com_password"
      prompt: "Password on Gitlab to download private Docker images. Leave blank if you do not have access to this information"
      private: yes

  roles:

    - role: mip-local
