- hosts: qatools
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    - role: sonarqube
      tags: ['sonarqube']

    - role: audit-deployment
      installed_component: qatools
      tags: ['sonarqube', 'marathon-app']
