---

# Postgresql user in Docker appears as user 999 outside
- name: Create Airflow database storage directory
  file: state=directory path={{ item }} mode=0700 owner={{ airflow_db_docker_user }} group={{ airflow_db_docker_user }}
  with_items:
    - '{{ airflow_db_data_dir }}'
    - '{{ airflow_db_docker_entrypoint_dir }}'

- name: Creation script for additional databases
  template:
    src: additional-databases.sql.j2
    dest: '{{ airflow_db_docker_entrypoint_dir }}/additional-databases.sql'

- name: Wait for Marathon
  include: ../../marathon-app/tasks/wait-for-marathon.yml
  vars:
    uri: "{{ internal_marathon_url }}"
  tags:
    - launch

- name: Remove old Airflow database using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ airflow_db_marathon_id }}"
    state: "absent"
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  tags:
    - launch

- name: Launch Airflow database using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ airflow_db_marathon_id }}"
    state: "present"
    docker_image: "{{ airflow_db_image }}:{{ airflow_db_version }}"
    docker_force_pull_image: true
    docker_network: BRIDGE
    docker_port_mappings:
      - hostPort: '{{ airflow_db_port }}'
        containerPort: 5432
        name: 'postgresql'
        protocol: 'tcp'
    container_volumes:
      - containerPath: "/var/lib/postgresql/data"
        hostPath: "{{ airflow_db_data_dir }}"
        mode: RW
      - containerPath: "/docker-entrypoint-initdb.d"
        hostPath: "{{ airflow_db_docker_entrypoint_dir }}"
        mode: RO
    env:
      POSTGRES_DB: "airflow"
      POSTGRES_USER: "{{ airflow_db_user }}"
      POSTGRES_PASSWORD: "{{ airflow_db_password }}"
      POSTGRES_ROOT_PASSWORD: "{{ airflow_db_root_password }}"
    labels:
      MARATHON_SINGLE_INSTANCE_APP: "true"
    instances: 1
    cpus: '{{ airflow_db_cpus }}'
    mem: '{{ airflow_db_mem }}'
    ports: [] # defined in docker_port_mappings
    require_ports: true
    constraints: [["hostname", "CLUSTER", "{{ airflow_db_marathon_host }}"]]
    dependencies: []
    executor: ""
    health_checks:
      - protocol: COMMAND
        command:
          value: "/usr/lib/postgresql/9.5/bin/pg_isready -U {{ airflow_db_user }} -p 5432"
        gracePeriodSeconds: 300
        intervalSeconds: 20
        timeoutSeconds: 10
        maxConsecutiveFailures: 5
    upgrade_strategy_minimum_health_capacity: 0.0
    upgrade_strategy_maximum_over_capacity: 0.0
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  tags:
    - launch
