---

- name: Should research-db be deployed in its own Postgres server?
  set_fact:
    do_research_db_deploy: "{{ research_db_deploy | bool }}"

- include: marathon.yml
  when: do_research_db_deploy

# run this task on the database host
- name: Wait for the database to be up and running
  wait_for: >
    port="{{ research_db_port }}"
    delay=2

- name: Drop database with name "research"
  postgresql_db:
    name: "{{ research_db_name }}"
    port: "{{ research_db_port }}"
    login_host: "{{ research_db_host }}"
    login_user: "{{ research_db_admin_user }}"
    login_password: "{{ research_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not do_research_db_deploy) and research_db_cleanup

- name: Create a new database with name "research"
  postgresql_db:
    name: "{{ research_db_name }}"
    port: "{{ research_db_port }}"
    login_host: "{{ research_db_host }}"
    login_user: "{{ research_db_admin_user }}"
    login_password: "{{ research_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create research user
  postgresql_user:
    login_host: "{{ research_db_host }}"
    login_user: "{{ research_db_admin_user }}"
    login_password: "{{ research_db_admin_password }}"
    db: "{{ research_db_name }}"
    port: "{{ research_db_port }}"
    name: "{{ research_db_user }}"
    password: "{{ research_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Create setup dir for the research database
  file:
    state: directory
    path: "{{ research_db_setup_dir }}"
  delegate_to: "{{ groups['control'][0] }}"
  when: research_db_fill

- name: Copy sql creation scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ research_db_setup_dir }}/{{ item.dest }}"
  with_items:
    - src: "{{ research_db_local_project_dir }}/sql/create.sql"
      dest: "V1_0__Create.sql"
  delegate_to: "{{ groups['control'][0] }}"
  when: research_db_fill

- name: Fix sql creation scripts
  replace:
    dest: "{{ research_db_setup_dir }}/V1_0__Create.sql"
    regexp: "/docker-entrypoint-initdb.d"
    replace: "/mnt"
  delegate_to: "{{ groups['control'][0] }}"
  when: research_db_fill

- name: Run Flyway migration
  docker_container:
    name: setup_research_db
    image: "hbpmip/flyway:{{ flyway_version }}"
    command: migrate
    detach: no
    network_mode: host
    interactive: yes
    # cleanup: yes
    volumes:
      - '{{ research_db_setup_dir }}:/flyway/sql'
    env:
      FLYWAY_DBMS: postgresql
      FLYWAY_HOST: '{{ research_db_host }}'
      FLYWAY_PORT: '{{ research_db_port }}'
      FLYWAY_DATABASE_NAME: '{{ research_db_name }}'
      FLYWAY_SCHEMAS: "public"
      FLYWAY_USER: '{{ research_db_admin_user }}'
      FLYWAY_PASSWORD: '{{ research_db_admin_password }}'
      FLYWAY_DRIVER: 'org.postgresql.Driver'
  delegate_to: "{{ groups['control'][0] }}"
  when: research_db_fill
