---
# Invariants for the configuration of Mesos leader (aka master) and users of Mesos

mesos_containerizers: "docker,mesos"
mesos_isolation: cgroups/cpu,cgroups/mem
mesos_resources:
  - "ports(*):[4000-5000, 31000-32000]"

mesos_zk_auth: "{% if zk_mesos_user_secret is defined %}{{ zk_mesos_user }}:{{ zk_mesos_user_secret }}@{% endif %}"
mesos_zk_dns: "{% for host in groups[zookeeper_server_group] %}{{ hostvars[host]['ansible_fqdn'] }}{% if not loop.last %},{% endif %}{% endfor %}"
mesos_zk_hosts: "{% for host in groups[zookeeper_server_group] %}{{ hostvars[host]['ansible_fqdn'] }}:{{ mesos_zk_port }}{% if not loop.last %},{% endif %}{% endfor %}"
mesos_zk_chroot: mesos
mesos_zk_base: "zk://{{ mesos_zk_auth }}{{ mesos_zk_hosts }}"
mesos_zk: "{{ mesos_zk_base }}/{{ mesos_zk_chroot }}"

marathon_zk_connect: "{{ mesos_zk_base }}/marathon"
