---

dev_services_db_marathon_id: /dev-services/dev-services-db

# Attach the Postgres database to a particular host. The hostname should be the name known by Marathon / Mesos
dev_services_db_marathon_host: '{{ inventory_hostname }}'

# The user running the Docker container for Postgres, default to '999' (postgres user in the Postgres docker container)
# TODO: use user remapping when this functionality will be available per run (not possible today with Docker 1.12)
dev_services_db_docker_user: '999'

postgres_version: "9.5.3"

dev_services_db_cpus: 0.5
dev_services_db_mem: 512.0

# Port exposed by Marathon, must be in the range [31000,32000[
dev_services_db_port: 31532
dev_services_db_host: localhost
dev_services_db_admin_user: postgres
# TO FILL - dev_services_db_admin_password:

dev_services_db_gitlab_user: "gitlab"
dev_services_db_sonarcube_user: "sonar"

# TO FILL - dev_services_db_gitlab_password:
# TO FILL - dev_services_db_sonarqube_password:

dev_services_db_data_dir: /srv/docker/portaldb/data

dev_services_db_setup_dir: /opt/portal-database/migration

# URL to marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: http://localhost:5080
