---

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task) and pip
  apt: name={{ item }} state=present
  with_items:
    - python-psycopg2
    - python-pip
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"

- name: Wait for the database to be up and running
  wait_for: >
    port="{{ analytics_db_port }}"
    delay=5
  delegate_to: "{{ groups['control'][0] }}"

- name: Create a new database with name "analytics"
  postgresql_db:
    name: analytics
    port: "{{ analytics_db_port }}"
    login_host: "{{ analytics_db_host }}"
    login_user: "{{ analytics_db_admin_user }}"
    login_password: "{{ analytics_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create analytics user
  postgresql_user:
    login_host: "{{ analytics_db_host }}"
    login_user: "{{ analytics_db_admin_user }}"
    login_password: "{{ analytics_db_admin_password }}"
    db: analytics
    port: "{{ analytics_db_port }}"
    name: "{{ analytics_db_user }}"
    password: "{{ analytics_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Create setup dir
  file:
    state: directory
    path: "{{analytics_db_setup_dir}}"

- name: Copy sql creation scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{analytics_db_setup_dir}}/{{ item.dest }}"
  with_items:
   - src: "analyticsdb/sql/create.sql"
     dest: "V1_0__Create-result-table.sql"

- name: Install Python module for Docker (required by docker_container task)
  pip: name=docker-py state=present
  delegate_to: "{{ groups['control'][0] }}"

- name: Run Flyway migration
  docker_container:
    name: flyway
    image: "lren/flyway:{{ flyway_version }}"
    command: migrate
    detach: no
    volumes:
      - '{{ analytics_db_setup_dir }}:/flyway/sql'
    env:
      FLYWAY_DBMS: postgres
      FLYWAY_HOST: '{{ analytics_db_host }}'
      FLYWAY_PORT: '{{ analytics_db_port }}'
      FLYWAY_DATABASE_NAME: '{{ analytics_db_admin_user }}'
      FLYWAY_USER: '{{ analytics_db_admin_user }}'
      FLYWAY_PASSWORD: '{{ analytics_db_admin_password }}'
  delegate_to: "{{ groups['control'][0] }}"
