---
#
# Master Install
#
# Installs _the_ world
#

- include: ../../common/playbooks/base-system.yml

- include: ../../common/playbooks/zookeeper.yml

- include: ../../common/playbooks/mesos-leader.yml

- include: ../../common/playbooks/mesos-mixed.yml

- include: ../../common/playbooks/mesos-follower.yml

- include: ../../common/playbooks/airflow.yml

- hosts: airflow
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/airflow.yml"

  tasks:

    - name: Create group for Airflow
      group:
        name: '{{ airflow_group }}'
        state: present

    - name: Create user for Airflow
      user:
        name: '{{ airflow_user }}'
        group: '{{ airflow_group }}'
        home: '{{ airflow_home }}'

    - name: Create folders for data and scripts
      file: path='{{ item }}' state=directory owner=airflow
      with_items:
        - /data/incoming/20160713

    - name: Get some MRI data
      git:
        repo: https://github.com/dcunited001/mri-scans.git
        dest: /data/incoming/20160713
        depth: 1

- hosts: cbrain
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    #- "{{ play_dir }}/vars/cbrain.yml"

  roles:

    - role: cbrain-database
      tags: ['cbrain']

    - role: cbrain-portal
      tags: ['cbrain']

    - role: cbrain-data-provider
      tags: ['cbrain']

    - role: cbrain-bourreau
      tags: ['cbrain']

    - role: audit-deployment
      installed_component: cbrain
      tags: ['cbrain']
