---

- include: marathon.yml
  when: mri_db_deploy

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl
  apt: name={{ item }} state=present
  with_items: '{{ mri_db_deb_packages }}'
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

# See https://github.com/anarcher/ansible-docker-registry/issues/1
- name: Make sure pip upgraded
  command: easy_install -U pip
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

- name: Install Python module for Docker (required by docker_container task)
  pip: name=docker-py state=present
  delegate_to: "{{ groups['control'][0] }}"

# run this task on the database host
- name: Wait for the mri database to be up and running
  wait_for: >
    port="{{ mri_db_port }}"
    delay=2

- name: Drop database with name "mri"
  postgresql_db:
    name: "{{ mri_db_name }}"
    port: "{{ mri_db_port }}"
    login_host: "{{ mri_db_host }}"
    login_user: "{{ mri_db_admin_user }}"
    login_password: "{{ mri_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not mri_db_deploy) and mri_db_cleanup

- name: Create a new database with name "mri"
  postgresql_db:
    name: "{{ mri_db_name }}"
    port: "{{ mri_db_port }}"
    login_host: "{{ mri_db_host }}"
    login_user: "{{ mri_db_admin_user }}"
    login_password: "{{ mri_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create mri user
  postgresql_user:
    login_host: "{{ mri_db_host }}"
    login_user: "{{ mri_db_admin_user }}"
    login_password: "{{ mri_db_admin_password }}"
    db: "{{ mri_db_name }}"
    port: "{{ mri_db_port }}"
    name: "{{ mri_db_user }}"
    password: "{{ mri_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Create group for Airflow
  group:
    name: '{{ airflow_group }}'
    state: present

- name: Create user for Airflow
  user:
    name: '{{ airflow_user }}'
    group: '{{ airflow_group }}'
    home: '{{ airflow_home }}'

- name: Create airflow home
  file:
    path: '{{ airflow_home}}'
    state: directory
    owner: '{{ airflow_user }}'

- name: Setup configuration for alembic database upgrade
  template:
    src: alembic.ini.j2
    dest: '{{ mri_meta_db_dir }}/alembic.ini'
    owner: '{{ airflow_user }}'

- name: Install pip
  apt:
    name: 'python-pip'
    state: present

- name: Install required Python packages
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - "SQLAlchemy==1.0.13"
    - "pydicom==0.9.9"
    - "alembic==0.8.6"

- name: Launch Alembic to upgrade the MRI database
  command: alembic upgrade head
  args:
    chdir: '{{ mri_meta_db_dir }}'
