---

- name: Wait for Marathon
  include: ../../marathon-app/tasks/wait-for-marathon.yml
  when: mri_db_deploy
  vars:
    uri: "{{ internal_marathon_url }}"
  tags:
    - launch

- name: Remove old MRI database using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ mri_db_marathon_id }}"
    state: "absent"
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  when: mri_db_deploy
  tags:
    - launch

- name: Optional cleanup
  file: state=absent path={{ mri_db_data_dir }}
  when: mri_db_deploy and mri_db_cleanup

# Postgresql user in Docker appears as user 999 outside
- name: Create MRI database storage directory
  file: state=directory path={{ item }} mode=0700 owner={{ mri_db_docker_user }} group={{ mri_db_docker_user }}
  with_items:
    - '{{ mri_db_data_dir }}'
    - '{{ mri_db_docker_entrypoint_dir }}'

- name: Copy sql creation scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ mri_db_docker_entrypoint_dir }}/{{ item.dest }}"
  with_items:
   - src: "mridb/sql/access.sql"
     dest: "access.sql"


- name: Launch MRI database using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ mri_db_marathon_id }}"
    state: "present"
    docker_image: "{{ mri_db_image }}:{{ mri_db_version }}"
    docker_force_pull_image: true
    docker_network: BRIDGE
    docker_port_mappings:
      - hostPort: '{{ mri_db_port }}'
        containerPort: 5432
        name: 'postgres'
        protocol: 'tcp'
    container_volumes:
      - containerPath: "/var/lib/postgresql/data"
        hostPath: "{{ mri_db_data_dir }}"
        mode: RW
      - containerPath: "/docker-entrypoint-initdb.d"
        hostPath: "{{ mri_db_docker_entrypoint_dir }}"
        mode: RO
    env:
      POSTGRES_USER: "{{ mri_db_admin_user }}"
      POSTGRES_PASSWORD: "{{ mri_db_admin_password }}"
    labels:
      MARATHON_SINGLE_INSTANCE_APP: "true"
      DATABASES: "{{ mri_db_databases }}"
    instances: 1
    cpus: '{{ mri_db_cpus }}'
    mem: '{{ mri_db_mem }}'
    ports: [] # defined in docker_port_mappings
    require_ports: true
    constraints: [["hostname", "CLUSTER", "{{ mri_db_marathon_host }}"]]
    dependencies: []
    executor: ""
    health_checks:
      - protocol: COMMAND
        command:
          value: "/usr/lib/postgresql/9.6/bin/pg_isready -U {{ mri_db_user }} -p 5432"
        gracePeriodSeconds: 300
        intervalSeconds: 20
        timeoutSeconds: 10
        maxConsecutiveFailures: 5
    upgrade_strategy_minimum_health_capacity: 0.0
    upgrade_strategy_maximum_over_capacity: 0.0
    wait_timeout: 600
  async: 600
  poll: 1
  delegate_to: "{{ groups['control'][0] }}"
  when: mri_db_deploy
  tags:
    - launch

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl
  apt: name={{ item }} state=present
  with_items:
    - python-psycopg2
    - python-pip
    - curl
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

# See https://github.com/anarcher/ansible-docker-registry/issues/1
- name: Make sure pip upgraded
  command: easy_install -U pip
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

- name: Install Python module for Docker (required by docker_container task)
  pip: name=docker-py state=present
  delegate_to: "{{ groups['control'][0] }}"

# run this task on the database host
- name: Wait for the mri database to be up and running
  wait_for: >
    port="{{ mri_db_port }}"
    delay=2

- name: Drop database with name "mri"
  postgresql_db:
    name: "{{ mri_db_name }}"
    port: "{{ mri_db_port }}"
    login_host: "{{ mri_db_host }}"
    login_user: "{{ mri_db_admin_user }}"
    login_password: "{{ mri_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not mri_db_deploy) and mri_db_cleanup

- name: Create a new database with name "mri"
  postgresql_db:
    name: "{{ mri_db_name }}"
    port: "{{ mri_db_port }}"
    login_host: "{{ mri_db_host }}"
    login_user: "{{ mri_db_admin_user }}"
    login_password: "{{ mri_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create mri user
  postgresql_user:
    login_host: "{{ mri_db_host }}"
    login_user: "{{ portal_db_admin_user }}"
    login_password: "{{ portal_db_admin_password }}"
    db: "{{ mri_db_name }}"
    port: "{{ mri_db_port }}"
    name: "{{ mri_db_user }}"
    password: "{{ mri_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

- name: Create group for Airflow
  group:
    name: '{{ airflow_group }}'
    state: present

- name: Create user for Airflow
  user:
    name: '{{ airflow_user }}'
    group: '{{ airflow_group }}'
    home: '{{ airflow_home }}'

- name: Create airflow home
  file:
    path: '{{ airflow_home}}'
    state: directory
    owner: '{{ airflow_user }}'

- name: Setup configuration for alembic database upgrade
  template:
    src: alembic.ini.j2
    dest: '{{ mri_meta_extract_dir }}/data/db/alembic.ini'
    owner: '{{ airflow_user }}'

- name: Install pip
  apt:
    name: 'python-pip'
    state: present

- name: Install required Python packages
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - "SQLAlchemy==1.0.13"
    - "pydicom==0.9.9"
    - "alembic==0.8.6"

- name: Launch Alembic to upgrade the MRI database
  command: alembic upgrade head
  args:
    chdir: '{{ mri_meta_extract_dir }}/data/db'
