---

- hosts: meta-db,meta-database
  become: yes
  gather_facts: no
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/reference/endpoints.yml"
    - "{{ play_dir }}/vars/reference/research-database.yml"
    - "{{ play_dir }}/vars/reference/meta-database.yml"

  roles:

    - role: meta-database
      tags: ['meta-database', 'meta-db', 'database', 'reference', 'marathon-app']

    - role: audit-deployment
      installed_component: reference-meta-database
      tags: ['meta-database', 'meta-db', 'database', 'reference', 'marathon-app']
