---

- name: Delete old version of SPM
  file:
    path: '{{ spm_install_root }}/spm{{ spm_version }}'
    state: absent

- name: Download and unpack SPM
  unarchive:
    src: '{{ spm_download_url }}'
    remote_src: yes
    validate_certs: '{{ spm_download_validate_url }}'
    dest: '{{ spm_install_root }}'
    creates: '{{ spm_install_root }}/spm{{ spm_version }}'

- name: Write local facts for SPM
  include: "{{ spm_path_to_lib_role }}/silpion.lib/tasks/localfacts.yml"
  vars:
    namespace: spm
    lib_action_become_enable: true
    lib_action_become_user: "root"
    lib_action_become_method: "sudo"
