---

- hosts: woken
  become: yes
  gather_facts: no
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/zookeeper.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/algorithm-factory/endpoints.yml"
    - "{{ play_dir }}/vars/algorithm-factory/chronos.yml"

  pre_tasks:

    - name: Install curl on control node - required for marathon-app
      apt: name=curl state=present
      delegate_to: "{{ groups['control'][0] }}"
      run_once: true
      tags: ['woken', 'analytics', 'algorithm-factory', 'af', 'marathon-app']

  roles:

    - role: chronos
      tags: ['chronos', 'analytics', 'algorithm-factory', 'af', 'marathon-app']

    - role: woken
      tags: ['woken', 'analytics', 'algorithm-factory', 'af', 'marathon-app']

    - role: audit-deployment
      installed_component: algorithm-factory-woken
      tags: ['woken', 'analytics', 'algorithm-factory', 'af', 'marathon-app']
