---

- include: marathon.yml
  when: data_catalog_db_deploy

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl
  apt: name={{ item }} state=present
  with_items: '{{ data_catalog_db_deb_packages }}'
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

- name: Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl
  yum: name={{ item }} state=present
  with_items: '{{ data_catalog_db_yum_packages }}'
  when: ansible_os_family == 'RedHat'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

# run this task on the database host
- name: Wait for the Data Catalog database to be up and running
  wait_for: >
    port="{{ data_catalog_db_port }}"
    delay=2

- name: Drop database with name "data_catalog"
  postgresql_db:
    name: "{{ data_catalog_db_name }}"
    port: "{{ data_catalog_db_port }}"
    login_host: "{{ data_catalog_db_host }}"
    login_user: "{{ data_catalog_db_admin_user }}"
    login_password: "{{ data_catalog_db_admin_password }}"
    state: absent
  delegate_to: "{{ groups['control'][0] }}"
  when: (not data_catalog_db_deploy) and data_catalog_db_cleanup

- name: Create a new database with name "data_catalog"
  postgresql_db:
    name: "{{ data_catalog_db_name }}"
    port: "{{ data_catalog_db_port }}"
    login_host: "{{ data_catalog_db_host }}"
    login_user: "{{ data_catalog_db_admin_user }}"
    login_password: "{{ data_catalog_db_admin_password }}"
    state: present
  delegate_to: "{{ groups['control'][0] }}"

- name: Create data_catalog user
  postgresql_user:
    login_host: "{{ data_catalog_db_host }}"
    login_user: "{{ data_catalog_db_admin_user }}"
    login_password: "{{ data_catalog_db_admin_password }}"
    db: "{{ data_catalog_db_name }}"
    port: "{{ data_catalog_db_port }}"
    name: "{{ data_catalog_db_user }}"
    password: "{{ data_catalog_db_password }}"
    role_attr_flags: "SUPERUSER"
  delegate_to: "{{ groups['control'][0] }}"

# See https://github.com/anarcher/ansible-docker-registry/issues/1
- name: Make sure pip upgraded
  command: easy_install -U pip
  when: ansible_os_family == 'Debian'
  delegate_to: "{{ groups['control'][0] }}"
  become: True

- name: Install Python module for Docker (required by docker_container task)
  pip: name=docker-py state=present
  delegate_to: "{{ groups['control'][0] }}"

- name: Run Alembic migration
  docker_container:
    name: migrate_data_catalog_db
    image: "{{ data_catalog_setup_image }}:{{ data_catalog_setup_version }}"
    command: upgrade head
    detach: no
    network_mode: host
    interactive: yes
    # cleanup: yes
    env:
      DB_URL: "{{ data_catalog_db_sql_alchemy_conn }}"
  delegate_to: "{{ groups['control'][0] }}"
