---
########################################
# First Five Minutes

# mesos-ui is not yet ready, kills deployment on ansible_os_family not defined.
skipped_roles: ["mesos-ui"]

ffm_timzone: "{{ ffm_timezone }}"
ffm_postfix_mode: "{{ tmr_postfix_mode }}"
# postfix smarthost only needed if ffm_postfix_mode equals "smarthost"
ffm_fqdn_smtp_relay: " {{ tmr_fqdn_smtp_relay }}"

unattended_mail: "{{ tmr_unattended_mail }}"
host_domain: "{{ tmr_host_domain }}"

use_host_domain: false

########################################
# Docker

# Overlay storage should help avoiding freezing Docker containers with a process that exits with error
# See https://github.com/docker/docker/issues/12738
# Also a kernel issue seems to be the cause
# See https://github.com/docker/docker/issues/18180#issuecomment-167042078
docker_opts: "--storage-driver=overlay2 --graph={{ docker_root_dir }} {{ tmr_dns_servers }}"
docker_root_dir: "/var/lib/docker"

#docker_registry_ip: "155.105.223.21"
#docker_registry_dns: "registry.federation.mip.hbp"
#docker_registry_marathon_host: "registry.federation.mip.hbp"

########################################
# Network

ssl_certs_common_name: "mip.humanbrainproject.eu"
ssl_certs_path: "/etc/ssl"
ssl_certs_privkey_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.private.key"
ssl_certs_cert_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.cert"

nginx_setup_ssl_certificate: true

########################################
# Zookeeper

zookeeper_version: 3.5.0
zookeeper_hosts:
  - host: "{{ tmr_hostname }}" # the machine running zookeeper
    id: 1

zookeeper_leader_port: "{{ tmr_zk_leader_port }}"
zookeeper_election_port: "{{ tmr_zk_election_port }}"

client_port: "{{ tmr_zk_port }}"

########################################
# Mesos Dual Leader/Follower configuration

#zookeeper_hostnames: "{{ groups['zookeeper'] | join(':' + tmr_zk_port|string + ',') }}:{{ tmr_zk_port }}"
zookeeper_hostnames: "{{ tmr_hostname }}:{{ tmr_zk_port }}"

mesos_hostname: "{{ tmr_hostname }}"
mesos_cluster: "mip_local_cluster"
mesos_containerizers: "docker,mesos"
mesos_leader_port: "{{ tmr_mesos_leader_port }}"
mesos_follower_port: "{{ tmr_mesos_follower_port }}"

mesos_zk_port: "{{ tmr_zk_port }}"
mesos_zk_base: "zk://{{ zookeeper_hostnames }}"
mesos_zk: "{{ mesos_zk_base }}/mesos"

internal_mesos_url: "http://{{ tmr_hostname }}:{{ mesos_leader_port }}"

########################################
# Marathon

marathon_hostname: "{{ tmr_hostname }}"
marathon_port: "{{ tmr_marathon_port }}"
marathon_zk_dns: "{{ tmr_hostname }}"
marathon_zk_port: "{{ tmr_zk_port }}"
marathon_zk_connect: "{{ mesos_zk_base }}/marathon"

internal_marathon_url: "http://{{ marathon_hostname }}:{{ marathon_port }}"
