#######################################################################
# 0. Technical Management Runtime

# All machines known to Ansible
[all]
host-mip-local-prod ip_address=10.0.2.15 ansible_connection=ssh ansible_host=m64006a327bae.dyn.epfl.ch ansible_port=2222 #if needed ansible_ssh_private_key_file=/home/sambuc/.ssh/id_rsa

# Managed hosts should contain all servers in the datacenter.
# Common software, configuration and security settings will be applied on them.
[managed]
host-mip-local-prod

# Control node: one control node should be selected, not necessarily in the datacenter - it can be the local desktop -
# but it should satisfy the following requirements:
# - direct network access to all services on the datacenter, in particular the databases and Marathon
# - Docker available on the control node
# - Possibility to install required packages (docker-py, curl...) for proper function of the Ansible tasks
[control]
host-mip-local-prod

[docker-registry]

[mesos-mixed]
host-mip-local-prod

[zookeeper]
host-mip-local-prod

[marathon]
#host-mip-local-prod

# So that variables are shared among all members of the meta-group
[technical-runtime:children]
docker-registry
mesos-mixed
zookeeper
marathon

#######################################################################
# 1. Data factory

# Install Airflow master (databases + webserver)
[airflow-master]
#host-mip-local-prod

# Install Airflow agent (scheduler + scripts + related applications like SPM)
[airflow-agent]
#host-mip-local-prod

# So that variables are shared among all members of the meta-group
[data-factory:children]
airflow-master
airflow-agent

#######################################################################
# 2. Hospital Databases Bundle

# Install PostgresRAW
[ldsm-db]
host-mip-local-prod

# So that variables are shared among all members of the meta-group
[hospital-databases-bundle:children]
ldsm-db

#######################################################################
# 3. Algorithm factory

[woken]
host-mip-local-prod

[woken-validation]
host-mip-local-prod

[analytics-db]
host-mip-local-prod

[mip-services]
host-mip-local-prod

[science-db]
host-mip-local-prod

[nodes]
host-mip-local-prod

# So that variables are shared among all members of the meta-group
[algorithm-factory:children]
woken
woken-validation
analytics-db
mip-services
science-db
nodes

#######################################################################
# 4. Web Portal

# Meta DB should be collocated with Portal DB
[meta-db]
host-mip-local-prod

[portal-db]
host-mip-local-prod

[portal-backend]
host-mip-local-prod

[portal-frontend]
host-mip-local-prod

# So that variables are shared among all members of the meta-group
[web-portal:children]
meta-db
portal-db
portal-backend
portal-frontend
