---

- name: Wait for Marathon
  include: ../../marathon-app/tasks/wait-for-marathon.yml
  vars:
    uri: "{{ internal_marathon_url }}"

- name: Remove old Portal backend using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ portal_backend_marathon_id }}"
    state: "absent"

- name: Launch Portal backend using Marathon
  marathon_app:
    uri: "{{ internal_marathon_url }}"
    id: "{{ portal_backend_marathon_id }}"
    state: "present"
    docker_image: "hbpmip/portal-backend:{{ portal_backend_version }}"
    env: '{{ portal_backend_env }}'
    instances: 1
    cpus: '{{ portal_backend_cpus }}'
    mem: '{{ portal_backend_mem }}'
    ports: []
    require_ports: false
    docker_parameters: '{{ portal_backend_docker_parameters }}'
    constraints: [["hostname", "CLUSTER", "{{ portal_backend_marathon_host }}"]]
    dependencies: ["{{ portal_db_marathon_id }}"]
    executor: ""
    user: "mip"
    wait_timeout: 600
    health_checks:
      - protocol: HTTP
        port: '{{ portal_backend_port }}'
        path: '{{ portal_backend_context_path }}/login/hbp'
        gracePeriodSeconds: 300
        intervalSeconds: 60
        timeoutSeconds: 20
        maxConsecutiveFailures: 2
  async: 600
  poll: 1
