---

- hosts: managed
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/base-system.yml"

  roles:
    - role: base-system
      tags: ['infra', 'infrastructure', 'runtimes']

    # Setup etckeeper and force it to use Git
    - role: etckeeper
      tags: ['infra', 'infrastructure', 'runtimes']

    - role: audit-deployment
      installed_component: infrastructure-base-system
      tags: ['infra', 'infrastructure', 'runtimes']
