---

- hosts: zookeeper
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"

  roles:

    # Java 8 is required for Zookeeper
    - role: openjdk
      tags: ['mesos-frameworks', 'marathon', 'runtimes']

    - role: zookeeper
      tags: ['mesos']

    - role: audit-deployment
      installed_component: zookeeper
      tags: ['mesos', 'container-platforms']
